name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    types: [opened, reopened, synchronize]

env:
  node-version: 18
  pnpm-version: 8

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup pnpm ${{ env.pnpm-version }}
        uses: pnpm/action-setup@v2
        with:
          version: ${{ env.pnpm-version }}

      - name: Setup Node.js ${{ env.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node-version }}
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Run check
        run: pnpm run check

      - name: Run lint
        run: pnpm run lint

  publish:
    if: github.ref == 'refs/heads/main'
    needs: checks
    environment:
      name: production
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup pnpm ${{ env.pnpm-version }}
        uses: pnpm/action-setup@v2
        with:
          version: ${{ env.pnpm-version }}

      - name: Setup Node.js ${{ env.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node-version }}
          cache: "pnpm"

      - name: Get version
        run: echo "PACKAGE_VERSION=$(node -p "require('./manifest.json').version")" >> $GITHUB_ENV

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm run build

      - name: Zip
        run: zip -r taby.zip dist

      - name: Publish release
        uses: softprops/action-gh-release@v1
        with:
          files: taby.zip
          tag_name: ${{ env.PACKAGE_VERSION }}
          body: "Take a look at the assets to download and install this app."
          draft: false
          prerelease: false

      - name: Publish to chrome web store
        run: |
          npx chrome-webstore-upload upload \
          --source taby.zip \
          --extension-id ${{ secrets.EXTENSION_ID }} \
          --client-id ${{ secrets.CLIENT_ID }} \
          --client-secret ${{ secrets.CLIENT_SECRET }} \
          --refresh-token ${{ secrets.REFRESH_TOKEN }}
